version: '3.2'

services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
      - "3035:3035"
    volumes:
      - .:/app:delegated
    command: bash -c "rm -f tmp/pids/server.pid && rails s -b 0.0.0.0"
